.gitignore, src/comportexviz/controls_ui.cljs, src/comportexviz/main.cljs, src/comportexviz/viz_canvas.cljs
Rather than having a draw loop, draw inside of the component's did-update React lifecycle method.
This makes the comportexviz canvas easier to reuse in other contexts, e.g. enabling multiple instances per page.
=> Make the viz and timeline canvases into self-drawing components.

examples/cortical_io/comportexviz/cortical_io_demo.cljs, examples/demos/comportexviz/demos/coordinates_2d.cljs, examples/demos/comportexviz/demos/fixed_seqs.cljs, examples/demos/comportexviz/demos/letters.cljs, examples/demos/comportexviz/demos/q_learning_1d.cljs, examples/demos/comportexviz/demos/q_learning_2d.cljs, examples/demos/comportexviz/demos/sensorimotor_1d.cljs, examples/demos/comportexviz/demos/simple_sentences.cljs, src/comportexviz/controls_ui.cljs, src/comportexviz/helpers.cljs, src/comportexviz/main.cljs, src/comportexviz/viz_canvas.cljs
Switch to a channel model for commands so that they can be sent to a particular canvas.
comportexviz.main still uses global atoms. Other consumers will use viz-canvas directly, providing their own atoms to viz-canvas.
Minor fix: use hiccup vectors, not function calls, for the `reagent/render`s so that component fns can return functions without causing confusing bugs with parameters.
=> Remove global atoms from viz-canvas, enable commands with multiple canvases

src/comportexviz/main.cljs, src/comportexviz/viz_canvas.cljs
Use the new htm-export in anticipation of new code that will need it.
Make viz-canvas more of a simple renderer of vectors of models by moving model-steps population completely to comportexviz.main.
=> Consume optional htm-export. Remove steps channel awareness from viz.

examples/cortical_io/comportexviz/cortical_io_demo.cljs, examples/demos/comportexviz/demos/coordinates_2d.cljs, examples/demos/comportexviz/demos/fixed_seqs.cljs, examples/demos/comportexviz/demos/letters.cljs, examples/demos/comportexviz/demos/q_learning_1d.cljs, examples/demos/comportexviz/demos/q_learning_2d.cljs, examples/demos/comportexviz/demos/second_level_motor.cljs, examples/demos/comportexviz/demos/sensorimotor_1d.cljs, examples/demos/comportexviz/demos/simple_sentences.cljs, src/comportexviz/controls_ui.cljs, src/comportexviz/helpers.cljs, src/comportexviz/main.cljs, src/comportexviz/plots.cljs, src/comportexviz/proxies.cljs, src/comportexviz/simulation/browser.cljs, src/comportexviz/simulation/common.cljs, src/comportexviz/simulation/remote.cljs, src/comportexviz/viz_canvas.cljs
This is initial work to enable visualizing external models without
having to dump the entire model into the browser.
In the current code it still requests the whole model via these
proxies. Subsequent changes will delay fetching of portions of the
model (e.g. synapse graphs), making parts of the rendering
asynchronous.
This change also:
- Made the :on-model-changed notification less fragile.
- Made the viz-canvas component stop eating commands after unmount.
Otherwise it becomes a big red herring when unexpected remounts
happen.
=> Access models via "proxies", init simulations in the per-page code

examples/cortical_io/comportexviz/cortical_io_demo.cljs, examples/demos/comportexviz/demos/coordinates_2d.cljs, examples/demos/comportexviz/demos/fixed_seqs.cljs, examples/demos/comportexviz/demos/letters.cljs, examples/demos/comportexviz/demos/q_learning_1d.cljs, examples/demos/comportexviz/demos/q_learning_2d.cljs, examples/demos/comportexviz/demos/runner.cljs, examples/demos/comportexviz/demos/second_level_motor.cljs, examples/demos/comportexviz/demos/sensorimotor_1d.cljs, examples/demos/comportexviz/demos/simple_sentences.cljs, project.clj, public/demos/runner.html, src/comportexviz/controls_ui.cljs, src/comportexviz/details.cljc, src/comportexviz/helpers.cljs, src/comportexviz/launchpad.clj, src/comportexviz/main.cljs, src/comportexviz/plots.cljs, src/comportexviz/server/browser.cljs, src/comportexviz/server/channel_proxy.cljc, src/comportexviz/server/journal.cljc, src/comportexviz/server/remote.cljs, src/comportexviz/server/runner.clj, src/comportexviz/server/simulation.cljc, src/comportexviz/util.cljc, src/comportexviz/viz_canvas.cljs
Design decision: Use Jetty's websockets. Don't hide them under
core.async, just use them directly. Don't use a library that attempts
to solve websockets for Clojure and ClojureScript, just use the raw
API in the browser. I think there'd be lots of wrestling with
libraries, e.g. in configuring Transit write-handlers and
read-handlers, and it just seems best to work closer to the core APIs
until we find a good reason not to.
Created a way of sending channels over the network via "channel
proxies". Note that this is not the same as treating the websocket
itself as a channel.
Got rid of "sim-options". It was too hard to synchronize an atom
between two machines without causing ping-ponging. Do everything via
into-sim and subscribing to play/pause status.
=> Visualize Comportex while it runs on the JVM

examples/cortical_io/comportexviz/cortical_io_demo.cljs, examples/demos/comportexviz/demos/coordinates_2d.cljs, examples/demos/comportexviz/demos/fixed_seqs.cljs, examples/demos/comportexviz/demos/letters.cljs, examples/demos/comportexviz/demos/q_learning_1d.cljs, examples/demos/comportexviz/demos/q_learning_2d.cljs, examples/demos/comportexviz/demos/runner.cljs, examples/demos/comportexviz/demos/second_level_motor.cljs, examples/demos/comportexviz/demos/sensorimotor_1d.cljs, examples/demos/comportexviz/demos/simple_sentences.cljs, project.clj, public/demos/runner.html, src/comportexviz/bridge/README.md, src/comportexviz/bridge/browser.cljs, src/comportexviz/bridge/channel_proxy.cljc, src/comportexviz/bridge/remote.cljs, src/comportexviz/controls_ui.cljs, src/comportexviz/main.cljs, src/comportexviz/plots.cljs, src/comportexviz/server/README.md, src/comportexviz/server/details.cljc, src/comportexviz/server/journal.cljc, src/comportexviz/server/launchpad.clj, src/comportexviz/server/runner.clj, src/comportexviz/server/simulation.cljc, src/comportexviz/viz_canvas.cljs
Remove all references to comportexviz.server from the Client code. It
talks to bridges. Bridges might talk to comportexviz.server code
(in-browser simulations), or might talk to remote servers.
Fix a bug where runner.html only worked in my dev environment. Oops.
=> Organize into "Server", "Bridge", and (default) Client

examples/demos/comportexviz/demos/second_level_motor.cljs, src/comportexviz/controls_ui.cljs, src/comportexviz/plots.cljs, src/comportexviz/server/data.cljc, src/comportexviz/server/journal.cljc
A first attempt. Matches active (learnable) cells to previously active sets of cells, i.e. SDRs. Shows predicted sequence transitions between these SDRs derived from connected distal synapses. This display is useful even just for distinguishing states in terms of cells, rather than the columns shown in the main display.
Currently the display shows distinct states in an order of first appearance. That is nice in that it is easy to interpret, but will not scale up well, and does not show similarity between SDRs. A force-directed graph layout might work as an option. The order-of-appearance one will need a scroll ability too.
The transitions-plot component has to keep track of the active cells each time step to match/update the SDRs it stores. That should maybe be moved to the server side to …
=> state transition diagram

src/comportexviz/controls_ui.cljs, src/comportexviz/helpers.cljs, src/comportexviz/plots.cljs, src/comportexviz/server/journal.cljc
This is a significant [low-hanging fruit] perf win for rendering.
Gather and aggregate the time series plot data independently of the
plots.
Now that the cell excitation plot doesn't render in the background,
there's no need to hide it behind a checkbox.
Use a resizing-canvas for the ts-freqs-plot. Tweak the plot-size to
use the whole canvas.
Fix a bug in canvas and resizing-canvas. They don't call the
most-recently-passed-in draw function, which is a problem when the
function refers to non-atom values via closures. Reagent makes it
really hard to render a canvas correctly.
I stared at the aggregation code for a while and came up with an
approach that uses only immutable values. Also, support non-keyword
keys in aggregate-by fn, though I didn't end up taking advantage of
this.
=> Stop rendering background tabs.

examples/demos/comportexviz/demos/notebook.cljs, src/comportexviz/main.cljs, src/comportexviz/server/data.cljc, src/comportexviz/server/journal.cljc, src/comportexviz/viz_canvas.cljs, src/comportexviz/viz_layouts.cljs
Rather than sizing the viz-canvas via CSS, let it size itself, and
impose limits via a max-height and max-width in the viz-options.
This is important for the notebook, where whitespace is gross.
This means we now resize this canvas via script, not CSS. With CSS it
would be difficult for the component to know whether it should
maintain its current size. Now there's a single pair of authoritative
numbers.
This required calculating the cells-segments layout before render,
similar to the other layouts. So the cells-segments layout now lives
inside viz-layouts.
I removed awareness of the source layout, bit, and dt from the
cells-segments layout. The method that uses those now takes them as
params. This matches other nearby usage, e.g. drawing distal synapses
from segments to other regions, …
=> Make the viz-canvas grow to fit its contents

examples/cortical_io/comportexviz/cortical_io_demo.cljs, examples/demos/comportexviz/demos/coordinates_2d.cljs, examples/demos/comportexviz/demos/fixed_seqs.cljs, examples/demos/comportexviz/demos/letters.cljs, examples/demos/comportexviz/demos/q_learning_1d.cljs, examples/demos/comportexviz/demos/q_learning_2d.cljs, examples/demos/comportexviz/demos/second_level_motor.cljs, examples/demos/comportexviz/demos/sensorimotor_1d.cljs, examples/demos/comportexviz/demos/simple_sentences.cljs, examples/worksheets/hello.clj, project.clj, src/comportexviz/controls_ui.cljs, src/comportexviz/helpers.cljs, src/comportexviz/plots.cljs, src/comportexviz/selection.cljs, src/comportexviz/server/data.cljc, src/comportexviz/server/details.cljc, src/comportexviz/server/journal.cljc, src/comportexviz/viz_canvas.cljs
Updates to work with nupic-community/comportex#26
Rename inputs to senses, etc.
=> Separate encoders from senses

examples/cortical_io/comportexviz/cortical_io_demo.cljs, examples/demos/comportexviz/demos/coordinates_2d.cljs, examples/demos/comportexviz/demos/fixed_seqs.cljs, examples/demos/comportexviz/demos/letters.cljs, examples/demos/comportexviz/demos/notebook.cljs, examples/demos/comportexviz/demos/q_learning_1d.cljs, examples/demos/comportexviz/demos/q_learning_2d.cljs, examples/demos/comportexviz/demos/runner.cljs, examples/demos/comportexviz/demos/second_level_motor.cljs, examples/demos/comportexviz/demos/sensorimotor_1d.cljs, examples/demos/comportexviz/demos/simple_sentences.cljs, src/comportexviz/bridge/browser.cljs, src/comportexviz/controls_ui.cljs, src/comportexviz/main.cljs, src/comportexviz/plots.cljs, src/comportexviz/util.cljc, src/comportexviz/viz_canvas.cljs
In the Runner, keep a single journal and simulation going, even if the model is reset. This means we can make `into-journal` and `into-sim` always be channels, not wrapped in atoms.
Fixes #27
Oh and I rewrote the fixed-seqs demo page to only show one demo, `isolated-1d`. The others don't really add much and may be confusing. And having different (infinite seq) input streams to switch between -- which was always icky -- really didn't work with this new arrangement.
=> Channels not in atoms

examples/worksheets/hello.clj, src/comportexviz/server/data.cljc
Respond to the change in https://github.com/nupic-community/comportex/pull/29
Definitely feel free to ask me to do `core/ff-base` differently. I sorta just added a core API on a whim.
=> Adjust to new core/predictions signature

examples/demos/comportexviz/demos/notebook.cljs, examples/demos/comportexviz/demos/runner.cljs, examples/worksheets/worksheet_shrink.clj, src/comportexviz/viz_canvas.cljs
Via React, it'll be easy to change the viz-canvas into a mashup of
canvas, divs, SVG, etc. I moved the top labels out of the canvas and
into the DOM. The benefit of this is that browsers are way better at
rendering text in the DOM than in canvases. It's especially noticeable
on Retina screens or when using pinch-to-zoom.
I think it'd be good to move all text labels out of the canvas, and
also write the viz-timeline in SVG (which has the same benefits, but
for shapes as well).
This change just handles the top labels, though, and updates the
notebook to keep it compatible.
=> Move some text out of the canvas and into the DOM

src/comportexviz/viz_canvas.cljs
Part 2 of my guilty-pleasure pixel changes.
Note that I've snuck in a small design change to both of these pull requests. The blank timeline and the input/region labels now appear immediately. They don't wait for the simulation to start.
=> SVG timeline. Also, scrollable timeline when necessary.

project.clj, src/comportexviz/controls_ui.cljs, src/comportexviz/plots.cljs, src/comportexviz/server/data.cljc, src/comportexviz/server/details.cljc, src/comportexviz/server/journal.cljc, src/comportexviz/viz_canvas.cljs
Corresponding change to nupic-community/comportex#35
support new parameters spec structure.
does not yet actually display apical dendrite segments. thinking of showing them side-by-side - each cell would have a vertical line of distal segments and to its right another vertical line of apical segments.
will need to alter the selection structure probably to distinguish distal from apical segments.
=> Handle apical dendrites

src/comportexviz/server/data.cljc, src/comportexviz/viz_canvas.cljs
Specify the source dt as part of a synapse.
This change was wonderfully simple/easy. I just want to check if you like this direction. Currently the client makes some assumptions about how HTM works. This change points to a future where, for example, we might show synapses going back 5 timesteps in a temporal pooling layer.
My real reason for making this change is something less glamorous. In nupic.research they pass pseudo feedback values directly into TemporalMemory, not using feedback from an actual feedforward-determined layer. So the best way to show this feedback input is just to show the apical synapses connecting to the current timestep rather than the previous. Or maybe I'm wrong, maybe I should just shift the inputs over one timestep, but that adds some messiness. Seems worth …
=> Allow servers to send synapses to back to arbitrary timesteps

src/org/numenta/sanity/comportex/data.cljc, src/org/numenta/sanity/comportex/journal.cljc, src/org/numenta/sanity/controls_ui.cljs, src/org/numenta/sanity/main.cljs, src/org/numenta/sanity/viz_canvas.cljs
Main changes:
- Use a cells -> segments -> synapses for all synapse types, even proximal.
Now the client and server both use a single set of functions for all synapse
types. data.cljc is now a lot prettier.
- Make the proximal synapse server API look very similar to distal/apical.
- Move proximal trace-back from the server to the client, so that all servers
get it for free, and so the server has a simpler API, allowing clients to do
what they want. Although it's slower to do this on the client. I think the
real fix for this slowness is to support querying multiple columns at once
rather than sending one message per column. I haven't started on this fix.
- Continue removing viz-options from messages. Send the syn-states instead.
This is working toward the goal of being able to remove …
=> Use one 'column-segs' and 'segment-syns' function for all synapse types

HOW-IT-WORKS.md, examples/cortical_io/org/numenta/sanity/cortical_io_demo.cljs, examples/demos/org/numenta/sanity/demos/hotgym.cljs, examples/demos/org/numenta/sanity/demos/letters.cljs, examples/demos/org/numenta/sanity/demos/notebook.cljs, examples/demos/org/numenta/sanity/demos/q_learning_1d.cljs, examples/demos/org/numenta/sanity/demos/q_learning_2d.cljs, examples/demos/org/numenta/sanity/demos/runner.cljs, examples/demos/org/numenta/sanity/demos/simple_sentences.cljs, src/org/numenta/sanity/bridge/marshalling.cljc, src/org/numenta/sanity/bridge/remote.cljs, src/org/numenta/sanity/comportex/README.md, src/org/numenta/sanity/comportex/data.cljc, src/org/numenta/sanity/comportex/journal.cljc, src/org/numenta/sanity/comportex/notebook.clj, src/org/numenta/sanity/comportex/runner.clj, src/org/numenta/sanity/comportex/simulation.cljc, src/org/numenta/sanity/comportex/websocket.clj, src/org/numenta/sanity/controls_ui.cljs, src/org/numenta/sanity/main.cljs, src/org/numenta/sanity/plots.cljs, src/org/numenta/sanity/util.cljc, src/org/numenta/sanity/viz_canvas.cljs
The main goal for this change is to make it where servers aren't inconvenienced
by the fact that Sanity is written in ClojureScript.
The overall approach: Clojure endpoints (e.g. the Sanity client and the
Comportex server) will use keywords internally. They use stringify-keys and
keywordize-keys, so all map keys just work. Some manual switching between
keywords and strings does happen because there are values that appear as both
keys and message params (namely, region IDs and layer IDs).
This change required me to form a point of view on keywords. I'll blog about it
here. :)
Clojure untangles a "keyword" type from the "string" type. The initial reason
for having a dedicated "keyword" is that it can do magic to support super-fast
equality checks. With keywords, a central instance table is …
=> Send strings, not keywords, across the network

HOW-IT-WORKS.md, examples/demos/org/numenta/sanity/demos/coordinates_2d.cljs, examples/demos/org/numenta/sanity/demos/cortical_io.cljs, examples/demos/org/numenta/sanity/demos/fixed_seqs.cljs, examples/demos/org/numenta/sanity/demos/hotgym.cljs, examples/demos/org/numenta/sanity/demos/letters.cljs, examples/demos/org/numenta/sanity/demos/notebook.cljs, examples/demos/org/numenta/sanity/demos/q_learning_1d.cljs, examples/demos/org/numenta/sanity/demos/q_learning_2d.cljs, examples/demos/org/numenta/sanity/demos/second_level_motor.cljs, examples/demos/org/numenta/sanity/demos/sensorimotor_1d.cljs, examples/demos/org/numenta/sanity/demos/simple_sentences.cljs, src/org/numenta/sanity/comportex/data.cljc, src/org/numenta/sanity/comportex/journal.cljc, src/org/numenta/sanity/controls_ui.cljs, src/org/numenta/sanity/main.cljs, src/org/numenta/sanity/plots.cljs, src/org/numenta/sanity/util.cljc, src/org/numenta/sanity/viz_canvas.cljs
Also rename the "step template" to the "network shape". The previous name
reflected my old design where each step got merged with its fetched data.
We now keywordize parts of the network shape when it arrives. Add this treatment
to the demos, unbreaking resets.
Also make the viz-canvas stop using the up-to-date network shape when fetching
bits. Instead, assoc the network shape onto the step so that we don't do
anything goofy after adding more regions and then selecting an old
step. Regardless of how important resetting is, this is elegant. Note that we
still do goofy things with segments if you select an old bit in a newly created
region.
=> Split "subscribe" into 3 messages. Fix and improve model resetting.

HOW-IT-WORKS.md, src/org/numenta/sanity/comportex/data.cljc, src/org/numenta/sanity/comportex/journal.cljc, src/org/numenta/sanity/viz_canvas.cljs
Sometimes we want to query for synapses on multiple columns, and it's slow to do
it one column at a time. The API ought to allow for batch queries.
Instead of patching batch queries on top, e.g. by making messages take in a list
of columns, this change solves the general problem. Fundamentally, we already
were serving segments / synapses in batches, just in a hardcoded way -- by
column, or by segment. This change gets rid of the hardcode. The sender can now
create advanced column / cell / segment selectors to specify what it wants.
I like that the API no longer feels like it was designed around Sanity's UI.
In cases where we query lots of columns / segments, using these batch queries is
a nice perf win, bringing us roughly back up to where we were when the server
did all the fetch logic.
=> The "seg-selector": making synapse / segment messages more powerful

src/org/numenta/sanity/viz_layouts.cljs
lay out 3D topologies as stacked 2D images (concatenated vertically).
It is also sometimes desirable to lay out 3D "stacked images" by interspersing bits from the multiple stacks at the corresponding position, so you can see how they line up. That could be done as an option but would require changing the display order of bits.
=> lay out 3D topologies as stacked 2D images.

examples/demos/org/numenta/sanity/demos/coordinates_2d.cljs, examples/demos/org/numenta/sanity/demos/cortical_io.cljs, examples/demos/org/numenta/sanity/demos/fixed_seqs.cljs, examples/demos/org/numenta/sanity/demos/hotgym.cljs, examples/demos/org/numenta/sanity/demos/letters.cljs, examples/demos/org/numenta/sanity/demos/q_learning_1d.cljs, examples/demos/org/numenta/sanity/demos/q_learning_2d.cljs, examples/demos/org/numenta/sanity/demos/runner.cljs, examples/demos/org/numenta/sanity/demos/second_level_motor.cljs, examples/demos/org/numenta/sanity/demos/sensorimotor_1d.cljs, examples/demos/org/numenta/sanity/demos/simple_sentences.cljs, src/org/numenta/sanity/controls_ui.cljs, src/org/numenta/sanity/main.cljs, src/org/numenta/sanity/viz_canvas.cljs
Pull the "selected-tab" state out of the tabs component.
Explanation: In some situations I want "capture" to be selected by default. In others I want "drawing", especially when doing a patchTM, when conservative "capture" options are no longer needed.
This also changes the timeline to always show line numbers, even when there are lots of steps. I should have made that change when I made the timeline scrollable.
=> Allow sanity-nupic to choose the selected tab
